openapi: 3.0.3
info:
  title: API design
  description: 'Some short description'
  contact:
    email: trungphuc94@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: User
    description: User
  - name: Game
    description: Game
  - name: Game Description
paths:
  /game:
    $ref: '/paths/game.yaml'
  /game/{game_id}:
    $ref: '/paths/game.{game_id}.yaml'
  /game-description:
    $ref: '/paths/game-description.yaml'