services:

  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      - ../db:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "capstone"

volumes:
  pgdata2:

