typeMappings:
  timestamp: Timestamp
importMappings:
  BaseResponse: com.cybersoft.capstone.payload.response.BaseResponse
  Coupon: com.cybersoft.capstone.dto.CouponDTO
  CouponStatus: com.cybersoft.capstone.entity.enums.CouponStatus
  Timestamp: java.sql.Timestamp
