openapi: 3.0.3
info:
  title: API design
  description: 'Some short description'
  contact:
    email: trungphuc94@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:8080/api
tags:
  - name: uer
    description: User
  - name: game
    description: Game
  - name: game_filter
    description: Game filters
  - name: game_description
paths:
  /game:
    $ref: './paths/game.yaml'
  /game/{game_id}:
    $ref: './paths/game.{game_id}.yaml'
  /game/filter:
    $ref: './paths/game.filter.yaml'
  /game-description:
    $ref: './paths/game-description.yaml'
