openapi: 3.0.3
info:
  title: API specification for Springboot Capstone project
  description: |-
    Short description
  #termsOfService: http://swagger.io/terms/
  contact:
    email: trungphuc94@gmail.com
  #license:
    #name: Apache 2.0
    #url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
#externalDocs:
  #description: Find out more about Swagger
  #url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: User
    description: User
    #externalDocs:
      #description: Find out more about our store
      #url: http://localhost:8080/api/v1/user
  - name: Game
    description: Game
paths:
  /game:
    get:
      tags:
        - Game
      summary: Get all games
      operationId: getAllGame
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        email:
          type: string
          example: john@email.com
        name:
          type: string
          example: 'Nguyen Van A'
        password:
          type: string
          example: '12345'
        address:
          type: string
          example: '123 Hung Vuong'
    GGame:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        is_dlc:
          type: boolean
          example: false
        game_dlc_id:
          type: integer
        title:
          type: string
        price:
          type: number
        realease_date:
          type: string
          format: date-time
        esrb_rating:
          type: string
          enum: [EVERYONE, EVERYONE_10, TEEN, MATURE, ADULT, PENDING, PENDING_17]
        is_deleted:
          type: boolean
        publisher_id:
          type: integer
        status:
          type: string
          enum: [DRAFT, VISIBLE, HIDDEN, ARCHIVED]
        description_id:
          type: integer
        developer_id:
          type: integer
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
